Vagrant.configure("2") do |config|

  config.vm.box = "p0m3lO/exam"
  config.vm.box_version = "1.1.2"
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--nic2", "intnet"]
    v.customize ["modifyvm", :id, "--intnet2", "exam_network"]
    v.name = "gde-exam"
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.define "exam" do |exam|
    exam.vm.hostname = "exam-vm"
    config.vm.network "private_network", ip: "192.168.20.10", virtualbox__intnet: "exam_network", auto_config: true, adapter: 2

		config.vm.network "forwarded_port", guest: 5000, host: 5000
		config.vm.network "forwarded_port", guest: 7681, host: 7681
  end
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update && sudo apt-get install -y curl git
    sudo wget https://github.com/tsl0922/ttyd/releases/download/1.7.3/ttyd.x86_64 -O /usr/local/bin/ttyd
    sudo chmod +x /usr/local/bin/ttyd
    su vagrant sh -c "exam --start"
  SHELL

end
